services:
  eshopfe:
    image: eshopfe
    build:
      context: .
    ports:
      - "80:80"
    restart: unless-stopped
    init: true
    depends_on: []
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
