export const environment = {
  registerUrl: 'https://stride-tag.onrender.com/auth/register',
  loginUrl: 'https://stride-tag.onrender.com/auth/login',
  userUrl: 'https://stride-tag.onrender.com/auth',
  allUserUrl: 'https://stride-tag.onrender.com/auth/findPageAllUsers',
  editRolesUrl: 'https://stride-tag.onrender.com/auth/updateRoles',
  productUrl: 'https://stride-tag.onrender.com/product',
  productPageUrl: 'https://stride-tag.onrender.com/product/fitraProdotti',
  categoryUrl: 'https://stride-tag.onrender.com/category',
  cartUrl: 'https://stride-tag.onrender.com/cart',
  orderUrl: 'https://stride-tag.onrender.com/order',
  resellerOrderUrl: 'https://stride-tag.onrender.com/resellerOrder',
  ticketUrl: 'https://stride-tag.onrender.com/Ticket',
  findTicketUrl: 'https://stride-tag.onrender.com/Ticket/findByUsername',
  editTicketUrl: 'https://stride-tag.onrender.com/Ticket/status',
  statsTicketUrl: 'https://stride-tag.onrender.com/Ticket/stats',
  ticketFilterUrl: 'https://stride-tag.onrender.com/Ticket/filtered',
};
