export const environment = {
  registerUrl: 'http://localhost:8080/auth/register',
  loginUrl: 'http://localhost:8080/auth/login',
  userUrl: 'http://localhost:8080/auth',
  allUserUrl: 'http://localhost:8080/auth/findPageAllUsers',
  productUrl: 'http://localhost:8080/product',
  productPageUrl: 'http://localhost:8080/product/fitraProdotti',
  categoryUrl: 'http://localhost:8080/category',
  cartUrl: 'http://localhost:8080/cart',
  orderUrl: 'http://localhost:8080/order',
  resellerOrderUrl: 'http://localhost:8080/resellerOrder',
  ticketUrl: 'http://localhost:8080/Ticket',
  findTicketUrl: 'http://localhost:8080/Ticket/findByUsername',
  editTicketUrl: 'http://localhost:8080/Ticket/status',
  statsTicketUrl: 'http://localhost:8080/Ticket/stats',
  ticketFilterUrl: 'http://localhost:8080/Ticket/filtered',
};
